# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: generate test coverage
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
    
    - name: check test coverage
    # You may pin to the exact commit or the version.
    # uses: vladopajic/go-test-coverage@bcd064e5ceef1ccec5441519eb054263b6a44787
      uses: vladopajic/go-test-coverage@v2.8.2
      with:
        profile: cover.out
        local-prefix: github.com/skyestalimit/diceroller
        threshold-file: 100
        threshold-package: 100
        threshold-total: 100
      
       
            
